name: CI

on:
  workflow_call:

jobs:
  CI:
    runs-on: ${{matrix.os}}
    env:
      GH_REPO_ACCESS_BY_OWN_APPS: ${{ secrets.GH_REPO_ACCESS_BY_OWN_APPS }}
      MYSQL_DATABASE: ${{vars.MYSQL_DATABASE}}
      MYSQL_ROOT_PASSWORD: ${{vars.MYSQL_ROOT_PASSWORD}}
      MYSQL_HOST:  ${{vars.MYSQL_HOST}}
      INSTALLER_USERID: ${{vars.INSTALLER_USERID}}
      INSTALLER_PWD: ${{vars.INSTALLER_PWD}}
      MYSQL_PWD: ${{vars.MYSQL_PWD}}
      MYSQL_TCP_PORT: ${{vars.MYSQL_TCP_PORT}}
      SQLALCHEMY_SILENCE_UBER_WARNING: 1
    strategy:
      fail-fast: true
      matrix:
#        python-version: [ '3.10', '3.11' ]
        python-version: [ '3.12' ]
        os: ['ubuntu-latest']
    services:
      mysql:
        image: mysql:8.0.25
        ports:
          - ${{vars.MYSQL_TCP_PORT}}:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-cmd="mysqladmin ping -h localhost -u root -p${{ vars.MYSQL_ROOT_PASSWORD }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        env:
          MYSQL_ROOT_PASSWORD: ${{vars.MYSQL_ROOT_PASSWORD}}
          MYSQL_DATABASE: ${{vars.MYSQL_DATABASE}}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

#      - name: Verify DB exists
#        run: mysql --host ${{env.MYSQL_HOST}} -uroot -p${{env.MYSQL_ROOT_PASSWORD}} -e "SHOW DATABASES"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

#      - name: Set PYTHONPATH
#        run: echo "PYTHONPATH=$PWD:$PWD/src/rtedb" >> $GITHUB_ENV

      - name: Install editable package
        run: pip install -e .[dev]

      - name: Run pytest
        run: pytest --cov=./

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
